version: '3.6'

services:

    backend:
      image: task1.12_back
      build: ./backend
      ports:
       - 8000:8000
      environment:
       - REDIS=redis
       - REDIS_PORT=6379
#       - DB_USERNAME=postgres
       - DB_PASSWORD=salasana
       - DB_NAME=testdb2
       - DB_host=post
       - FRONT_URL=http://localhost
      container_name: backend

      depends_on:
       - postgres
       - redis

      restart: on-failure

    frontend:
      image: task1.12_front
      build: ./frontend
      ports:
       - 5000:5000
      container_name: frontend
      environment:
        - API_URL=http://localhost/api

    redis:
      image: redis
      ports:
        - 6379:6379

    postgres:
      image: postgres:latest
#      restart: unless-stopped
      environment:
#       - POSTGRES_USER=testi
       - POSTGRES_PASSWORD=salasana
       - POSTGRES_DB=testdb2
      container_name: postgres
      ports:
        - 3306:3306
      volumes:
        - ./database:/var/lib/postgresql/data

    proxy:
      image: nginx
      ports:
        - 80:80
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      restart: on-failure

#    adminer:
#      image: adminer
#      restart: always
#      environment:
#        - ADMINER_DESIGN=galkaev
#      ports:
#        - 8083:8080

#    redmine:
#      image: redmine
#      environment:
#        - REDMINE_DB_POSTGRES=testdb
#        - REDMINE_DB_PASSWORD=sana
#      ports:
#        - 9999:3000
#      volumes:
#        - files:/usr/src/redmine/files
#      depends_on:
#        - post

#volumes:
#  files:
